version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nestjs-mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjsrealworld
      MYSQL_USER: nestjsuser
      MYSQL_PASSWORD: nestjspassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nestjs-network

  app:
    build: .
    container_name: nestjs-app-container
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:watch
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  mysql_data: 