name: continuous-integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Set npm registry to official
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
            
      - name: Set custom DATABASE_URL
        run: echo 'DATABASE_URL="mysql://mysql:f9f6cff4c6c4071a9b5c@painel.eduardoabrito.com.br:3031/nestjsrealworld"' > prisma/.env

      - name: Run Prisma migrations and generate client
        run: |
          npx prisma migrate deploy --schema=prisma/schema.prisma
          npx prisma generate --schema=prisma/schema.prisma

      - name: Copy config and build project
        run: |
          cp src/config.ts.example src/config.ts
          npm run build

      - name: Run integration tests
        run: npm run test:integration
