name: continuous-integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nestjsrealworld-prisma
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Set npm registry to official
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Copy Prisma env file
        run: cp prisma/.env.example prisma/.env

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h mysql --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run Prisma migrations and generate client
        run: |
          npx prisma migrate deploy --schema=prisma/schema.prisma
          npx prisma generate --schema=prisma/schema.prisma

      - name: Copy config and build project
        run: |
          cp src/config.ts.example src/config.ts
          npm run build

      - name: Run integration tests
        run: npm run test:integration
